title: "UC Berkeley Data Storage Options"
description: "An unofficial guide to data storage options provided by UC Berkeley."
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
