name: Check Markdown links

on:
  push:
  schedule:
    # Runs at 00:00 on the 1st day of every month
    - cron: '0 0 1 * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
